spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://10.20.26.247:33061/mybatis_plus_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver